[2023-03-21 08:56:04,116] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: querry_postgres_v1.4.insert_querry_postgres_table manual__2023-03-21T07:52:34.606843+00:00 [queued]>
[2023-03-21 08:56:04,162] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: querry_postgres_v1.4.insert_querry_postgres_table manual__2023-03-21T07:52:34.606843+00:00 [queued]>
[2023-03-21 08:56:04,164] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 08:56:04,165] {taskinstance.py:1239} INFO - Starting attempt 6 of 7
[2023-03-21 08:56:04,166] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 08:56:04,208] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): insert_querry_postgres_table> on 2023-03-21 07:52:34.606843+00:00
[2023-03-21 08:56:04,215] {standard_task_runner.py:52} INFO - Started process 2285 to run task
[2023-03-21 08:56:04,224] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'querry_postgres_v1.4', 'insert_querry_postgres_table', 'manual__2023-03-21T07:52:34.606843+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/querry_posgresql.py', '--cfg-path', '/tmp/tmptlyjgpiz', '--error-file', '/tmp/tmpu1avcxel']
[2023-03-21 08:56:04,228] {standard_task_runner.py:77} INFO - Job 278: Subtask insert_querry_postgres_table
[2023-03-21 08:56:04,601] {logging_mixin.py:109} INFO - Running <TaskInstance: querry_postgres_v1.4.insert_querry_postgres_table manual__2023-03-21T07:52:34.606843+00:00 [running]> on host 0b4cdb459521
[2023-03-21 08:56:04,788] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 349, in call
    return __obj(*args, **kwargs)
TypeError: 'TaskInstance' object is not callable
[2023-03-21 08:56:04,889] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=querry_postgres_v1.4, task_id=insert_querry_postgres_table, execution_date=20230321T075234, start_date=20230321T085604, end_date=20230321T085604
[2023-03-21 08:56:04,934] {standard_task_runner.py:92} ERROR - Failed to execute job 278 for task insert_querry_postgres_table
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 349, in call
    return __obj(*args, **kwargs)
TypeError: 'TaskInstance' object is not callable
[2023-03-21 08:56:04,993] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-03-21 08:56:05,199] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
