[2023-03-20 19:01:58,963] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table_user manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:01:59,000] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table_user manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:01:59,001] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:01:59,002] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 19:01:59,002] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:01:59,040] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_user> on 2023-03-20 19:01:39.369448+00:00
[2023-03-20 19:01:59,046] {standard_task_runner.py:52} INFO - Started process 23011 to run task
[2023-03-20 19:01:59,055] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.9', 'create_postgres_table_user', 'manual__2023-03-20T19:01:39.369448+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmpi1lmhycr', '--error-file', '/tmp/tmpcrzg61w5']
[2023-03-20 19:01:59,058] {standard_task_runner.py:77} INFO - Job 237: Subtask create_postgres_table_user
[2023-03-20 19:01:59,348] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.9.create_postgres_table_user manual__2023-03-20T19:01:39.369448+00:00 [running]> on host 0b4cdb459521
[2023-03-20 19:01:59,663] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.9
AIRFLOW_CTX_TASK_ID=create_postgres_table_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T19:01:39.369448+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T19:01:39.369448+00:00
[2023-03-20 19:01:59,741] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 19:01:59,816] {dbapi.py:225} INFO - Running statement: 
            create table if not exists user1 (
                user_id text PRIMARY KEY,
                name text,
                review_count text,
                useful int,
                funny int,
                cool int,
                elite text,
                friends text,
                fans text,
                average_stars float,
                yelping_since_values date
            ) 
        , parameters: None
[2023-03-20 19:01:59,821] {postgres.py:71} INFO - NOTICE:  relation "user1" already exists, skipping

[2023-03-20 19:01:59,909] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.9, task_id=create_postgres_table_user, execution_date=20230320T190139, start_date=20230320T190158, end_date=20230320T190159
[2023-03-20 19:01:59,987] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 19:02:00,221] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
