[2023-03-20T02:02:36.462+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: to_posgrest_v1.create_postgres_table manual__2023-03-20T01:52:26.676828+00:00 [queued]>
[2023-03-20T02:02:36.481+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: to_posgrest_v1.create_postgres_table manual__2023-03-20T01:52:26.676828+00:00 [queued]>
[2023-03-20T02:02:36.483+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T02:02:36.486+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 6
[2023-03-20T02:02:36.487+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T02:02:36.507+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-03-20 01:52:26.676828+00:00
[2023-03-20T02:02:36.516+0000] {standard_task_runner.py:55} INFO - Started process 735 to run task
[2023-03-20T02:02:36.520+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v1', 'create_postgres_table', 'manual__2023-03-20T01:52:26.676828+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmp1hlrg1yp']
[2023-03-20T02:02:36.524+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask create_postgres_table
[2023-03-20T02:02:36.607+0000] {task_command.py:388} INFO - Running <TaskInstance: to_posgrest_v1.create_postgres_table manual__2023-03-20T01:52:26.676828+00:00 [running]> on host 5443d245a01a
[2023-03-20T02:02:36.662+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T01:52:26.676828+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T01:52:26.676828+00:00
[2023-03-20T02:02:36.663+0000] {sql.py:254} INFO - Executing: 
            create table if not exists temperature (
                date DATE PRIMARY KEY,
                min DECIMAL(5, 2),
                max DECIMAL(5, 2),
                normal_min DECIMAL(5, 2),
                normal_max DECIMAL(5, 2),
                mean DECIMAL(5, 2),
                status_temp int64
            )
        
[2023-03-20T02:02:36.673+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-03-20T02:02:36.814+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-03-20T02:02:39.872+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[2023-03-20T02:02:39.905+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=to_posgrest_v1, task_id=create_postgres_table, execution_date=20230320T015226, start_date=20230320T020236, end_date=20230320T020239
[2023-03-20T02:02:39.922+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 31 for task create_postgres_table (server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
; 735)
[2023-03-20T02:02:39.939+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T02:02:39.962+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
